### ISSUE TITLE
Query coin symbol if cannot find CMC name

### ISSUE THREAD

**Issue by tonyin** [CityOfZion/neo-discord-bot#21]
eg. `!coincap btc` would query the symbol if it cannot find the name, and return the same results as `!coincap bitcoin`

**Comment by drptbl** [comment]
I've already added a `coinDictionary` function on my personal branch which resolves this issue:
https://github.com/drptbl/neo-discord-bot/blob/calendar-command/helpers.js#L16
Example of usage (in new command which prints events from `coinmarketcal`):
https://github.com/drptbl/neo-discord-bot/blob/calendar-command/imports/commands/general/calendar.js#L30
How it works in details:
https://github.com/drptbl/neo-discord-bot/blob/calendar-command/helpers.js#L41
Using this you can find a coin using it's symbol, full name or even id.

However I'm not able to get this done until #20 is merged (it s implementing breaking-changes to the bot). As soon as it's merged, `!coincap` command will be improved.

**Comment by drptbl** [comment]
Should be done in #27.
